name: Push validation

on:
  push:
    branches:
      - main
      - 'release/**'
    tags:
      - '*'

permissions:
  contents: read

jobs:
  validate:
    uses: ./.github/workflows/validate.yaml

